# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [AFAN, JUUL]
patreon: # Replace with a single Patreon username tictok
open_collective: # Replace with a single Open Collective username hunters.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel -runtime 
community_bridge: # Replace with a single Community Bridge project-name e.g., TOR-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username chime
otechie: # Replace with a single Otechie username 40rounds
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://truth.org','https://Creativecommons.org','https://3m.com','https://chaturbate.com/huntertiana/','https://www.theguardian.com/commentisfree/2020/aug/04/coronavirus-pandemic-wave-wildfire','https://open.spotify.com/user/31jkn2lrh7ey2rlqs3ennptjyfma?si=JNfTfGL5TLWauhPbEnRgvA','https://sans.org/security-awareness']
