name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: marceloctorres/COVID-19 
        path: target
        
    - uses: actions/checkout@v2
      with:
        repository: CSSEGISandData/COVID-19
        path: source
        
    - name: Pull Request .
      run: |
        cd target
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        echo $GITHUB_TOKEN
        
        echo 'git remote -v'
        git remote -v

        echo "git remote set-url origin 'https://marceloctorres$GITHUB_TOKEN@github.com/marceloctorres/COVID-19.git'"
        git remote set-url origin 'https://marceloctorres:m4rc3l025202$$@github.com/marceloctorres/COVID-19.git'
        
        echo "git remote add upstream 'https://CSSEGISandData/COVID-19.git'"
        git remote add upstream 'https://CSSEGISandData/COVID-19.git'
        
        echo "git remote -v"
        git remote -v
        
        echo "hub pull-request"
        hub pull-request \
          -b origin
          -h upstream
         --no-edit 
