name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: marceloctorres/COVID-19 
        path: target
        
    - uses: actions/checkout@v2
      with:
        repository: CSSEGISandData/COVID-19
        path: source
        
    - name: Pull Request .
      run: |
        cd target
        GITHUB_TOKEN=${{ secrets.TOKEN }}
        git remote -v
        
        git remote set-url origin 'https://marceloctorres:$GITHUB_TOKEN@github.com/marceloctorres/COVID-19.git'
        git remote add upstream 'https://CSSEGISandData/COVID-19.git'
        git remote -v
        
        hub init -g
        hub pull-request \
          -b origin
          -h upstream
         --no-edit 
