name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: marceloctorres/COVID-19 
        path: target
        
    - uses: actions/checkout@v2
      with:
        repository: CSSEGISandData/COVID-19
        path: source
        
    - name: Pull Request .
      run: |
        cd target
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"      
        git remote add upstream https://github.com/CSSEGISandData/COVID-19.git
        git pull upstream master
        git add .
        git commit -m 'Automatico'
        git push origin master
        git request-pull -p '30ce7eb' https://marceloctorres/COVID-19 master
 
