name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: target
        
    - uses: actions/checkout@v2
      with:
        repository: CSSEGISandData/COVID-19
        path: target
        
    - name: Pull Request
      run: |
        cd target
        git request-pull -p master https://marceloctorres/COVID-19 master
 
