name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: target
        
    - uses: actions/checkout@v2
      with:
        repository: CSSEGISandData/COVID-19
        path: source

    - name: Github Pull Request
      uses: repo-sync/pull-request@master
      id: pull-request
      with:
        source_branch: source   
        destination_branch: target
        pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "marceloctorres"                     # Comma-separated list (no spaces)
        pr_assignee: "marceloctorres"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        pr_milestone: "Milestone 1"                       # Milestone name
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
